name: Build and Deploy Eleventy

on:
  push:
    branches: [ "main" ]  # 每次推送到 main 时自动构建
  workflow_dispatch:      # 可手动触发

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 25.0.0

      - name: Install dependencies
        run: npm i -g @11ty/eleventy && npm ci
      - name: Build site
        run: npx @11ty/eleventy

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
